node {
  stage('Terraform Build') {
    git credentialsId: 'bc4cdd02-8691-46c4-bb93-20278a920677', url: 'git@bitbucket.org:project/project.git'
    dir("infrastructure/terraform/configurations/${APPLICATION}") {
      hash = "${HASH}".trim()
      sh "terraform init"
      sh "terraform workspace select ${ENVIRONMENT} || terraform workspace new ${ENVIRONMENT}"
      sh """terraform apply -var 'hash=${hash}'"""
    }
  }
}
