node {
  stage('Build Image') {

    git credentialsId: 'bc4cdd02-8691-46c4-bb93-20278a920677', url: 'git@bitbucket.org:project/project.git'
    sh "chmod 600 /var/jenkins_home/.ssh/id_rsa"
    sh "ssh-agent bash -c 'ssh-add /var/jenkins_home/.ssh/id_rsa'"

    dir("containers/${APPLICATION}") {
      hash = "${HASH}".trim()
      app = docker.build("123.dkr.ecr.eu-west-2.amazonaws.com/project/${ENVIRONMENT}/${APPLICATION}:${hash}")
    }
  }

  stage('AWS Login') {
    sh """aws ecr get-login --region eu-west-2 > login.txt"""
    sh """cut -d' ' -f1-6,9- login.txt | sh"""
  }

  stage('Push Image') {
    sh """docker push 123.dkr.ecr.eu-west-2.amazonaws.com/project/${ENVIRONMENT}/${APPLICATION}:${hash}"""
  }
}
