FROM sonarqube:latest


RUN wget https://github.com/SonarSource/SonarTS/releases/download/v1.0.0/sonar-typescript-plugin-1.0.0.340.jar -P /opt/sonarqube/extensions/plugins
RUN wget https://github.com/Backelite/sonar-swift/releases/download/0.3.5/backelite-sonar-swift-plugin-0.3.5.jar -P /opt/sonarqube/extensions/plugins
